application: twitbubbles
version: 1
runtime: php
api_version: 1

handlers:
- url: /styles
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /
  script: bubbles.php

- url: /.*
  script: error.php